/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class project_JNIproject */

#ifndef _Included_project_JNIproject
#define _Included_project_JNIproject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     project_JNIproject
 * Method:    Sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_project_JNIproject_Sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     project_JNIproject
 * Method:    Subtract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_project_JNIproject_Subtract
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     project_JNIproject
 * Method:    Multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_project_JNIproject_Multiply
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     project_JNIproject
 * Method:    Divide
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_project_JNIproject_Divide
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
